#!/bin/bash
SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")
cat > /opt/anchor/.env << EOF
DB_USER=anchor
DB_PASSWORD=Anch0r_DB_2024!
DB_HOST=db
DB_PORT=5432
DB_NAME=anchor
DATABASE_URL=postgresql+asyncpg://anchor:Anch0r_DB_2024!@db:5432/anchor
REDIS_URL=redis://redis:6379/0
BROKER_PROVIDER=ibkr
IBKR_HOST=ib_gateway
IBKR_PORT=4004
IBKR_CLIENT_ID=1
IBKR_PAPER_ACCOUNT_ID=DUP564728
IBKR_PAPER_USERNAME=fxjkdo981
IBKR_ACCOUNT_ALIAS=paper
IBKR_EXCHANGE_FOREX=IDEALPRO
IBKR_EXCHANGE_CRYPTO=PAXOS
IBKR_MARKET_DATA_TYPE=1
TWS_USERID=fxjkdo981
TWS_PASSWORD=change_me
TWS_ACCEPT_INCOMING=accept
TRADING_MODE=paper
READ_ONLY_API=no
VNC_SERVER_PASSWORD=change_me_vnc
AUTO_RESTART_TIME=
RELOGIN_AFTER_2FA_TIMEOUT=no
TIME_ZONE=Etc/UTC
POLYGON_API_KEY=your_polygon_api_key_here
FRED_API_KEY=your_fred_api_key_here
TELEGRAM_BOT_TOKEN=your_telegram_bot_token
TELEGRAM_CHAT_ID=your_telegram_chat_id
APP_ENV=production
SECRET_KEY=${SECRET}
LOG_LEVEL=INFO
GRAFANA_PASSWORD=Anch0r_Graf_2024!
MAX_RISK_PER_TRADE=0.01
MAX_DAILY_LOSS=0.03
DRAWDOWN_REDUCE_PCT=0.08
DRAWDOWN_HALT_PCT=0.15
MIN_CONFLUENCE_SCORE=0.65
MIN_ML_CONFIDENCE=0.58
EOF
echo "Done. Contents:"
cat /opt/anchor/.env
