"""Prometheus metrics definitions.

All metrics defined here. Import and use throughout the codebase.
Exposed at /metrics endpoint via prometheus-client.
"""
from __future__ import annotations

from prometheus_client import Counter, Gauge, Histogram, Summary

# ── Trading metrics ─────────────────────────────────────────────────────────
signals_generated = Counter(
    "anchor_signals_generated_total",
    "Total signals generated by confluence engine",
    ["instrument", "direction"],
)

signals_suppressed = Counter(
    "anchor_signals_suppressed_total",
    "Signals suppressed before order submission",
    ["instrument", "reason"],
)

orders_submitted = Counter(
    "anchor_orders_submitted_total",
    "Orders submitted to broker",
    ["instrument", "direction"],
)

orders_filled = Counter(
    "anchor_orders_filled_total",
    "Orders successfully filled",
    ["instrument", "direction"],
)

orders_rejected = Counter(
    "anchor_orders_rejected_total",
    "Orders rejected by broker",
    ["instrument", "reason"],
)

trades_closed = Counter(
    "anchor_trades_closed_total",
    "Trades closed",
    ["instrument", "close_reason"],
)

# ── P&L metrics ──────────────────────────────────────────────────────────────
account_balance = Gauge(
    "anchor_account_balance_usd",
    "Current account balance in USD",
)

account_equity = Gauge(
    "anchor_account_equity_usd",
    "Current account equity (balance + unrealized P&L)",
)

unrealized_pl = Gauge(
    "anchor_unrealized_pl_usd",
    "Total unrealized P&L across all open positions",
)

drawdown_pct = Gauge(
    "anchor_drawdown_pct",
    "Current drawdown as percentage of peak equity",
)

# ── Position metrics ─────────────────────────────────────────────────────────
open_positions = Gauge(
    "anchor_open_positions",
    "Number of currently open positions",
    ["instrument"],
)

# ── Regime metrics ───────────────────────────────────────────────────────────
regime_state = Gauge(
    "anchor_regime_state",
    "Current regime state (0=RANGING, 1=TRENDING, 2=VOLATILE)",
    ["instrument"],
)

# ── ML metrics ───────────────────────────────────────────────────────────────
ml_confidence = Gauge(
    "anchor_ml_confidence",
    "Last ML confidence score per instrument",
    ["instrument"],
)

ood_detections = Counter(
    "anchor_ood_detections_total",
    "Out-of-distribution feature vector detections",
    ["instrument"],
)

# ── System metrics ───────────────────────────────────────────────────────────
heartbeat_age_seconds = Gauge(
    "anchor_heartbeat_age_seconds",
    "Seconds since last heartbeat was written",
)

api_request_duration = Histogram(
    "anchor_api_request_duration_seconds",
    "API request latency",
    ["method", "endpoint"],
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0],
)

websocket_connections = Gauge(
    "anchor_websocket_connections",
    "Number of active WebSocket connections",
)

reconciliation_discrepancies = Counter(
    "anchor_reconciliation_discrepancies_total",
    "Position reconciliation discrepancies found",
    ["type"],
)
